# this is an image scanning workflow from https://sysdig.com/blog/image-scanning-github-actions/


name: Build and scan Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest
    - name: Scan image
      uses: sysdiglabs/scan-action@v3.4.0
      with:
        image-tag: "sysdiglabs/dummy-vuln-app:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        sysdig-secure-url: https://us2.app.sysdig.com
        dockerfile-path: ./Dockerfile
        input-type: docker-daemon
        run-as-user: root
        ignore-failed-scan: false
